name: Generate Page Extension

on:
  push:
    paths:
      - "src/*.al"
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2


      - name: Detect table extensions
        id: detect
        run: |
          # Find files matching your naming style
          FILES=$(find src -maxdepth 1 -type f -iname "Tab-Ext*.al" || true)

          echo "Detected files:"
          echo "$FILES"

          # Make it available to later steps
          echo "table_ext<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT




      - name: Create Page Extensions
        if: steps.detect.outputs.table_ext != ''
        run: |
          while IFS= read -r FILE; do
            NAME=$(basename "$FILE" .al)
            PAGE_FILE="src/${NAME}PageExt.al"

            echo "Creating $PAGE_FILE"

            cat <<EOF > "$PAGE_FILE"
            pageextension ${NAME}PageExt extends "Vendor Card"
            {
            }
            EOF

            done <<< "${{ steps.detect.outputs.table_ext }}"


      - name: Commit generated files
        if: steps.detect.outputs.table_ext != ''
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git add src/*PageExt.al

          if git diff --cached --quiet; then
            echo "Nothing to commit."
            exit 0
          fi

          git commit -m "Auto-create page extension"
          git push
